updated json_handler
- new tests required
- test error in  code profile-> lin 124:

Traceback (most recent call last):
File "C:\Users\annemieke\Desktop\TIJDELIJK\1. GIS
zaken\GitHub\TijhuisArcGisTools\external\gistools\test\test_json_handler.py",
line 47, in test_fielddata_to_memcollections
point_col, line_col, ttlr_col = fielddata_to_memcollections(json_file)
File "C:\Users\annemieke\Desktop\TIJDELIJK\1. GIS
zaken\GitHub\TijhuisArcGisTools\external\gistools\utils\json_handler.py",
line 124, in fielddata_to_memcollections
for p in profile.get('measured_profiles'):
TypeError: 'NoneType' object is not iterable